<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AcploLog\Log\AbstractLogger'    => __DIR__ . '/src/AcploLog/Log/AbstractLogger.php',
    'AcploLog\Log\EntityLogger'      => __DIR__ . '/src/AcploLog/Log/EntityLogger.php',
    'AcploLog\Log\ErrorLogger'       => __DIR__ . '/src/AcploLog/Log/ErrorLogger.php',
    'AcploLog\Log\Loggable'          => __DIR__ . '/src/AcploLog/Log/Loggable.php',
    'AcploLog\Log\LoggableObject'    => __DIR__ . '/src/AcploLog/Log/LoggableObject.php',
    'AcploLog\Log\SqlLogger'         => __DIR__ . '/src/AcploLog/Log/SqlLogger.php',
    'AcploLog\Log\StaticLogger'      => __DIR__ . '/src/AcploLog/Log/StaticLogger.php',
    'AcploLog\Options\ModuleOptions' => __DIR__ . '/src/AcploLog/Options/ModuleOptions.php',
);
